export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
};

export const CART_ACTION_TYPES = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
  INCREASE_CART_ITEM: 'INCREASE_CART_ITEM',
};

export const DIRECTORY_ACTIONS = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
};

export const SHOP_ACTIONS = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESSFUL: 'FETCH_COLLECTIONS_SUCCESSFUL',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
};
