export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
};

export const CART_ACTION_TYPES = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
  INCREASE_CART_ITEM: 'INCREASE_CART_ITEM',
};
